Error when SQS_INPUT_QUEUE_URL not found

diff --git a/.bin/aws-sqs-poll b/.bin/aws-sqs-poll
--- a/.bin/aws-sqs-poll
+++ b/.bin/aws-sqs-poll
@@ -14,7 +14,12 @@ function main() {
   shift
 
   export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-"us-east-1"}"
-  local SQS_INPUT_QUEUE_URL="${SQS_INPUT_QUEUE_URL}"
+
+  local SQS_INPUT_QUEUE_URL="${SQS_INPUT_QUEUE_URL:-}"
+  if [[ -z "${SQS_INPUT_QUEUE_URL}" ]]; then
+    echo "Missing SQS_INPUT_QUEUE_URL" >&2
+    return 1
+  fi
 
   while true; do
 
